# Generated by Django 4.2.22 on 2025-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_variant"),
        ("orders", "0002_colordictionary_pricedictionary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="notes",
            field=models.ManyToManyField(blank=True, to="cart.note"),
        ),
    ]
