# Generated by Django 4.2.22 on 2025-06-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
