# Generated by Django 4.2.22 on 2025-06-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DictionaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="مثلاً كود HEX للألوان أو اختصار المقاس",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("C", "Color"), ("S", "Size")], max_length=1
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "item_type")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("totalstock", models.PositiveIntegerField(default=0)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("simple", "Simple"),
                        ],
                        default="modern",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "C"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="color_variants",
                        to="products.dictionaryitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "S"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="size_variants",
                        to="products.dictionaryitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "color", "size")},
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الموقع"
                    ),
                ),
                ("logo", models.URLField(blank=True, null=True)),
                ("landing_cover", models.URLField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="العملة"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم واتساب"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, null=True, verbose_name="معلومات عن الموقع"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="فيسبوك"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="انستجرام"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="تويتر"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, null=True, verbose_name="يوتيوب"),
                ),
                (
                    "tiktok",
                    models.URLField(blank=True, null=True, verbose_name="تيك توك"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="لينكدإن"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("index", models.PositiveIntegerField(default=0)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="LandingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("html_code", models.TextField()),
                ("index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "key")},
            },
        ),
    ]
