# Generated by Django 4.2.22 on 2025-06-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"item_type": "C"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_variants",
                to="products.dictionaryitem",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"item_type": "S"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="size_variants",
                to="products.dictionaryitem",
            ),
        ),
    ]
