# Generated by Django 4.2.22 on 2025-06-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productvariant_color_alter_productvariant_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="youtube_video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
