# Generated by Django 4.2.22 on 2025-06-13 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_youtube_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hex_code", models.CharField(blank=True, max_length=7, null=True)),
                ("cost", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DictionaryProductName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Add"),
                            ("remove", "Remove"),
                            ("adjust", "Adjust"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="files/images_Product/Item/%Y/%m/%d/",
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("cost", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="color",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="size",
        ),
        migrations.RemoveField(
            model_name="variantimage",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_code",
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="files/images/products/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_alarm",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="settings",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="currency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="site_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DictionaryItem",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
        migrations.DeleteModel(
            name="VariantImage",
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.size",
            ),
        ),
    ]
