# Generated by Django 4.2.22 on 2025-06-16 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_youtube_video_url_product_youtube_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$", "Invalid hex color code"
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="color",
            index=models.Index(fields=["name"], name="products_co_name_502f66_idx"),
        ),
    ]
