# Generated by Django 4.2.22 on 2025-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_categories_alter_product_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_url",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(blank=True, null=True, to="products.product"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logo/"),
        ),
    ]
