# Generated by Django 4.2.22 on 2025-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_delete_productimage_remove_category_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="landing_cover",
            field=models.ImageField(blank=True, null=True, upload_to="logo/"),
        ),
    ]
