# Generated by Django 4.2.22 on 2025-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_settings_landing_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="landing_cover",
            field=models.ImageField(blank=True, null=True, upload_to="cover/"),
        ),
    ]
