# Generated by Django 4.2.22 on 2025-06-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_settings_landing_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="theme",
            field=models.CharField(
                choices=[
                    ("modern", "Modern"),
                    ("classic", "Classic"),
                    ("simple", "Simple"),
                    ("amazon", "Amazon"),
                ],
                default="simple",
                max_length=50,
            ),
        ),
    ]
