# Generated by Django 4.2.22 on 2025-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
