# Generated by Django 4.2.22 on 2025-06-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="size",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size",
                to="products.product",
            ),
        ),
    ]
