# Generated by Django 4.2.22 on 2025-06-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_color_product_size_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="color",
            old_name="cost",
            new_name="stock",
        ),
        migrations.RenameField(
            model_name="size",
            old_name="cost",
            new_name="stock",
        ),
    ]
