# Generated by Django 4.2.22 on 2025-06-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variant",
        ),
    ]
