# Generated by Django 4.2.22 on 2025-06-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_color_product_size_product"),
        ("cart", "0002_remove_cartitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
            ),
        ),
    ]
