# Generated by Django 4.2.22 on 2025-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipping_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="files/images/Item/%Y/%m/%d/"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("shipping_price", models.FloatField(default=0)),
                ("discount_price", models.FloatField(default=0)),
                ("work_days", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="shipping_Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("tax", models.IntegerField(default=0)),
                (
                    "Shipping",
                    models.ManyToManyField(blank=True, to="shipping.shipping_company"),
                ),
            ],
        ),
    ]
