# Generated by Django 4.2.22 on 2025-06-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagelibrary",
            name="categories",
        ),
        migrations.AddField(
            model_name="imagelibrary",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="media_library.imagecategory",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="imagelibrary",
            constraint=models.UniqueConstraint(
                fields=("title", "category"), name="unique_image_title_per_category"
            ),
        ),
    ]
