# Generated by Django 4.2.22 on 2025-06-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("governorate", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                (
                    "shipping_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "purchase_count",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("total_spending", models.FloatField(default=0)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipping.shipping_country",
                    ),
                ),
            ],
        ),
    ]
