# Generated by Django 4.2.22 on 2025-10-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
